"""ss

Revision ID: d031253bc662
Revises: bfae272d894c
Create Date: 2017-08-15 16:56:32.034971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd031253bc662'
down_revision = 'bfae272d894c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'we_zchina_article_cates', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_articles', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_articles', 'we_zchina_article_cates', ['cate_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_module_functions', 'we_zchina_modules', ['module_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_function_services', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_function_services', 'we_zchina_product_functions', ['function_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_function_services', 'we_zchina_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_function_services', 'we_zchina_module_functions', ['module_function_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_functions', 'we_zchina_module_functions', ['module_function_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_functions', 'we_zchina_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_product_services', 'we_zchina_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_solution_services', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_solution_services', 'we_zchina_solutions', ['solution_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_user_auths', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_user_certs', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_user_logs', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_user_types', 'we_zchina_users', ['zchina_user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_users', 'we_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'we_zchina_users', 'we_zchinas', ['wezchina_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'we_zchina_users', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_users', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_user_types', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_user_logs', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_user_certs', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_user_auths', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_solution_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_solution_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_functions', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_functions', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_function_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_function_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_function_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_product_function_services', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_module_functions', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_articles', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_articles', type_='foreignkey')
    op.drop_constraint(None, 'we_zchina_article_cates', type_='foreignkey')
    # ### end Alembic commands ###
